DOC Note that module is not compatible with CMS5
spekulatius/silverstripe-composer-security-checker pull request #60
Opened 2023-06-15 22:29 UTC by sabina-talipova

## Parent issue
- https://github.com/silverstripe/.github/issues/25

2023-06-20 08:11 UTC, maxime-rainville approved these changes

2023-06-20 08:12 UTC, maxime-rainville requested changes
Can we remove the `silverstripe|supported` badge below?

2023-06-20 20:20 UTC, sabina-talipova commented
Updated

2023-06-21 21:03 UTC, maxime-rainville approved these changes

2023-06-21 21:05 UTC, merged